# PREREQUISITES
# pip install mysql-connector   (not required)
# pip install mysql-connector-python==8.0.6
# CREATE USER 'chatbot'@'%' IDENTIFIED BY 'XXXXXXX';
# GRANT ALL PRIVILEGES ON *.* TO 'chatbot'@'%' WITH GRANT OPTION;

import mysql.connector

mysqldb = mysql.connector.connect(
	host = "server-00616",
	port = 3305,
	user = "chatbot",
	passwd = "XXXXXXX",
	database = "quotations",
	auth_plugin='mysql_native_password')

mycursor = mysqldb.cursor()

mycursor.execute("""CREATE TABLE registration (mobile           VARCHAR(50),
                                               pol_no           INT,
                                               pol_year         INT,
                                               media            VARCHAR(150),
                                               reg_no           VARCHAR(50),
                                               timestamp        DATETIME)""")

mycursor.execute("""CREATE TABLE chatbot (mobile           VARCHAR(50),
                                          menu             INT,
                                          timestamp        DATETIME)""")                                               

mycursor.execute("""CREATE TABLE tba (pol_no           INT,
                                      pol_year         INT,
                                      registration     VARCHAR(50),
                                      timestamp        DATETIME)""")   

mycursor.execute("""CREATE TABLE policies (mobile           VARCHAR(50),
                                           pol_no           INT,
                                           pol_year         INT,
                                           exp_date         DATETIME,
                                           renewal_prem     Float,
                                           selection        INT,
                                           timestamp        DATETIME)""")

mycursor.execute("""CREATE TABLE pol_details (timestamp      DATETIME,         
                                              office_desc    VARCHAR(50),       
                                              source         VARCHAR(50),       
                                              class_desc     VARCHAR(50),       
                                              pol_type_desc  VARCHAR(100),      
                                              policy_no      INT,               
                                              policy_year    INT,               
                                              endt_no        INT,               
                                              endt_year      INT,               
                                              intermediary   VARCHAR(255),      
                                              client         VARCHAR(255),      
                                              insured        VARCHAR(255),      
                                              cust_no        INT,               
                                              eff_dt         DATETIME,         
                                              exp_dt         DATETIME,         
                                              ren_dt         DATETIME,         
                                              mobile         VARCHAR(50),       
                                              agent_no       INT,               
                                              agent_comm     FLOAT,             
                                              pol_type       INT,               
                                              veh_make       INT,               
                                              veh_model      INT,               
                                              body_type      INT,               
                                              plate_type     INT,               
                                              class_of_use   INT,               
                                              reg_no         VARCHAR(50),       
                                              year_of_make   INT,               
                                              seats          INT,               
                                              chassis        VARCHAR(50),       
                                              engine_cc      INT,               
                                              agency_repair  INT,               
                                              rsa_provider   INT,               
                                              tariff         INT,
                                              agent_name     VARCHAR(250))""")

mycursor.execute("""ALTER TABLE pol_details CHARACTER SET utf8 COLLATE UTF8_general_ci""")

mycursor.execute("""CREATE TABLE all_endts (timestamp      DATETIME,     
                                            endt_no        INT,               
                                            endt_year      INT,  
                                            endt_type      INT,
                                            endt_trans     INT,
                                            pol_no         INT,               
                                            pol_year       INT,  
                                            pol_type       VARCHAR(150), 
                                            source         INT,
                                            endt_dt        DATETIME,
                                            ins_st         DATETIME,
                                            ins_ed         DATETIME,
                                            uw_year        INT,
                                            client_no      INT,
                                            client_name    VARCHAR(255),
                                            cust_no        INT,
                                            cust_name      VARCHAR(255),
                                            net_prem       FLOAT,
                                            discounts      FLOAT,
                                            loadings       FLOAT,
                                            rsa_prem       FLOAT,
                                            issue_fee      FLOAT,
                                            total_prem     FLOAT,
                                            vat_amount     FLOAT,
                                            final_total    FLOAT,
                                            si             FLOAT)""")
                                           
mycursor.execute("""CREATE TABLE renewals (timestamp                DATETIME,                  
                                           BRANCH                   INT,
                                           OFFICE                   INT,
                                           CLASS_OF_BUSINESS        INT,
                                           POLICY_TYPE              INT,
                                           ENDT_TYPE                INT,
                                           TRN_TYPE                 INT,
                                           ISSUE_DATE               DATETIME,
                                           PAYMENT_MODE             INT,
                                           HIJRI_EFF_DATE           VARCHAR(50),
                                           HIJRI_EXP_DATE           VARCHAR(50),
                                           EFF_DATE                 DATETIME,
                                           EXP_DATE                 DATETIME,
                                           CLIENT_CODE              INT,
                                           CLIENT_ENAME             VARCHAR(255),
                                           CLIENT_ANAME             VARCHAR(255),
                                           INSURED_ENAME            VARCHAR(255),
                                           INSURED_ANAME            VARCHAR(255),
                                           BROKER                   VARCHAR(100),
                                           BROKER_COMM_PCNT         INT,
                                           BROKER_COMM_AMT          FLOAT,
                                           ID_NO                    VARCHAR(50),
                                           OCCUPATION               VARCHAR(50),
                                           NATIONALITY              VARCHAR(50),
                                           CITY                     VARCHAR(50),
                                           HOME_TEL                 VARCHAR(50),
                                           OFFICE_TEL               VARCHAR(50),
                                           MOBILE                   VARCHAR(50),
                                           DOB                      VARCHAR(50),
                                           AGE                      VARCHAR(50),
                                           VEHICLE_MAKE             INT,
                                           VEHICLE_MODEL            INT,
                                           TYPE_OF_BODY             INT,
                                           PLATE_TYPE               VARCHAR(50),
                                           EVCL_CUSTOM_ID           VARCHAR(50),
                                           CLASS_OF_USE             INT,
                                           PLATE_NO                 VARCHAR(50),
                                           ENGINE_NO                VARCHAR(50),
                                           NO_OF_CYLINDERS          VARCHAR(50),
                                           YEAR_OF_MAKE             INT,
                                           SEATING_CAPACITY         INT,
                                           SI                       INT,
                                           RATE                     VARCHAR(50),
                                           BASIC_PREM               INT,
                                           TOTAL_PREM               INT,
                                           NET_PREM                 INT,
                                           ADD_PREM                 INT,
                                           DISCOUNT                 INT,
                                           DEPRECIATION             VARCHAR(50),
                                           CHASSIS_NO               VARCHAR(50),
                                           REMARKS                  VARCHAR(50),
                                           ADDRESS                  VARCHAR(250),
                                           BUS_LOCATION             INT,
                                           VEHICLE_COLOR            VARCHAR(50),
                                           DEDUCTABLE               VARCHAR(50),
                                           ENGINE_CAPACITY          INT,
                                           PER_ACC_DRV              INT,
                                           PAD_COVER_PCNT           INT,
                                           PAD_COVER_AMT            INT,
                                           PER_ACC_DRV_PASS         INT,
                                           PADP_COVER_PCNT          INT,
                                           PADP_COVER_AMT           INT,
                                           AGENCY_REPAIR            INT,
                                           ER_COVER_PCNT            INT,
                                           ER_COVER_AMT             INT,
                                           CON_NAT                  INT,
                                           CN_COVER_PCNT            INT,
                                           CN_COVER_AMT             INT,
                                           BETWEEB_AGE              INT,
                                           BA_COVER_PCNT            INT,
                                           BA_COVER_AMT             INT,
                                           LESSTHAN_AGE             INT,
                                           LA_COVER_PCNT            INT,
                                           LA_COVER_AMT             INT,
                                           ADJUST_FLAG              INT,
                                           CUST_ZIP_CODE            VARCHAR(50),
                                           CUST_PO_BOX              VARCHAR(50),
                                           DRIVER_NAME              VARCHAR(255),
                                           AGENCY_FLAG              INT,
                                           USER_ID                  VARCHAR(50),
                                           POL_NO                   INT,
                                           POL_YEAR                 INT,
                                           ENDT_NO                  INT,
                                           ENDT_YEAR                INT,
                                           DRIVER_BIRTH_DT          VARCHAR(50),
                                           DRIVER_IQAMA_NO          VARCHAR(50),
                                           DRIVER_LICENSE_TYPE      VARCHAR(50),
                                           REF_NO                   VARCHAR(50),
                                           BROKER_NO                INT,
                                           SOURCE                   INT,
                                           POST_FLAG                INT,
                                           ENDT_DT                  TIMESTAMP,
                                           CLIENT_VOH_TYPE          INT,
                                           CLIENT_VOH_YEAR          INT, 
                                           CLIENT_VOH_NO            INT,
                                           AGENT_VOH_TYPE           INT,
                                           AGENT_VOH_YEAR           INT,
                                           AGENT_VOH_NO             INT,
                                           CUST_NO                  INT,
                                           AGENT_NO                 INT,
                                           AGENT_NAME               VARCHAR(250),
                                           AGENT_COMM_AMT           INT,
                                           SERVICE_CHARGE           INT,
                                           ADD_TAX                  INT,
                                           ISSUE_FEE                INT,
                                           STAMP_FEE                INT,
                                           ICF_FEE                  INT,
                                           GATR_PREM                INT,
                                           REI_FLAG                 INT,
                                           ERR_FLAG                 INT,
                                           SEQUENCE_NO              VARCHAR(50),
                                           RSA_PROVIDER             VARCHAR(50),
                                           BENEFICIARY_NO           VARCHAR(50),
                                           CUST_CLASS               VARCHAR(50),
                                           DISC_CODE                INT,
                                           DISC_PCNT                INT,
                                           NCB_FLAG                 INT,
                                           NCB_AMT                  INT,
                                           LOADING_CODE             INT,
                                           LOADING_PCNT             INT,
                                           LOADING                  INT,
                                           LOAD_AMT                 INT,
                                           TARIFF_PKG               INT,
                                           ENDO_SERIAL              INT,   
                                           VAT_PCNT                 INT,
                                           VAT_AMT                  FLOAT,
                                           FINAL_TOT_AMT            FLOAT,
                                           VAT_COMM_PCNT            INT,
                                           VAT_COMM_AMT             INT,
                                           VEHICLE_SERIAL           INT,
                                           FILE_NO                  VARCHAR(50))""")     

mycursor.execute("""CREATE TABLE schedule (timestamp                DATETIME,                  
                                           LANG                     VARCHAR(50),
                                           BRANCH                   INT,
                                           OFFICE                   INT,
                                           CLASS_OF_BUSINESS        INT,
                                           ENDT_NO                  INT,
                                           ENDT_YEAR                INT,
                                           ENDT_TYPE                INT,
                                           POL_NO                   INT,
                                           POL_YEAR                 INT,
                                           BROKER                   VARCHAR(150),
                                           POLICY_NO                VARCHAR(150),
                                           POLICY_TYPE              VARCHAR(150),
                                           EFF_DATE                 DATETIME,
                                           EXP_DATE                 DATETIME,
                                           ISSUE_DATE               DATETIME,
                                           INSURED                  VARCHAR(250),
                                           ADDRESS                  VARCHAR(250),
                                           VEHICLE_MAKE             VARCHAR(150),
                                           VEHICLE_MODEL            VARCHAR(150),
                                           REGISTRATION_NO          VARCHAR(150),
                                           CHASSIS_NO               VARCHAR(150),
                                           YEAR_OF_MAKE             INT,
                                           CLASS_OF_USE             VARCHAR(150),
                                           SEATING_CAPACITY         INT,
                                           VALUE                    VARCHAR(150),
                                           DEDUCTIBLE               INT,
                                           EXCESS                   VARCHAR(50),
                                           BUS_LOC                  VARCHAR(150),
                                           BUS_LOCATION             INT,
                                           COVERS                   VARCHAR(250),
                                           EXCLUSIONS               VARCHAR(150),
                                           ACCESSORIES              VARCHAR(150),
                                           VOH_NO                   INT,
                                           VOH_YEAR                 INT,
                                           ADDITIONAL_COVER         VARCHAR(250),
                                           ADDITIONAL_CONDITIONS    VARCHAR(250),
                                           CUST_NO                  INT,  
                                           BODY_TYPE                VARCHAR(150),
                                           TAZUR_VAT                VARCHAR(100),
                                           TOTAL_PREM               FLOAT,
                                           VAT_PCNT                 FLOAT,
                                           VAT_AMT                  FLOAT,
                                           TOTAL_FINAL              FLOAT,
                                           RSA                      VARCHAR(250),
                                           CUST_ACC                 VARCHAR(150),
                                           CUST_VAT                 VARCHAR(150))""")   

mycursor.execute("""CREATE TABLE endt_details (timestamp                DATETIME,
                                               endt_no                  INT,
                                               endt_year                INT,
                                               class_of_business        INT,
                                               endt_type                INT,
                                               office                   INT,
                                               branch                   INT,
                                               pol_type                 INT,
                                               endt_dt                  DATETIME,
                                               client_no                INT,
                                               client_name              VARCHAR(250),
                                               cust_name                VARCHAR(250),
                                               cust_tel_no              INT,
                                               cust_address             VARCHAR(250),
                                               agent_no                 INT,
                                               comm                     FLOAT,
                                               comm_amt                 FLOAT,
                                               ins_st                   DATETIME,
                                               ins_ed                   DATETIME,
                                               endt_st_dt               DATETIME,
                                               si                       FLOAT,
                                               rate                     FLOAT,
                                               gross_prem               FLOAT,
                                               discounts                FLOAT,
                                               add_prem                 FLOAT,
                                               remarks                  VARCHAR(250),
                                               total_prem               FLOAT,
                                               cust_job                 INT,
                                               client_aname             VARCHAR(250),
                                               cust_aname               VARCHAR(250),
                                               cust_birth_dt            DATETIME,
                                               hijri_st_dt              DATETIME,
                                               hijri_ed_dt              DATETIME,
                                               pol_hijri_st_dt          DATETIME,
                                               bus_location             INT,
                                               cust_id_no               VARCHAR(50),
                                               cust_nationality         INT,
                                               cust_city                INT,
                                               cust_tel                 VARCHAR(50),
                                               cust_mobile              VARCHAR(50),
                                               cust_zimg_code           VARCHAR(50),
                                               cust_po_box              VARCHAR(50),
                                               vehicle_make             INT,
                                               vehicle_model            INT,
                                               type_of_body             INT,
                                               plate_type               INT,
                                               class_of_use             INT,
                                               vehicle_color            INT,
                                               chassis_no               VARCHAR(100),
                                               year_of_make             INT,
                                               no_of_cylender           INT,
                                               registration_no          VARCHAR(100),
                                               seat_capacity            INT,
                                               depreciation             FLOAT,
                                               deductable               FLOAT,
                                               engine_capacity          INT,
                                               engine_no                VARCHAR(150),
                                               adjust_flag              INT,
                                               payment_term             INT,
                                               sequence_no              INT,
                                               ref_no                   VARCHAR(100),
                                               issue_fee                FLOAT,
                                               service_charge           FLOAT,
                                               add_driver_name          VARCHAR(250),
                                               add_driver_license_type  VARCHAR(100),
                                               add_driver_birth_dt      DATETIME,
                                               custom_id                INT,
                                               add_driver_iqama_no      VARCHAR(100),
                                               status                   INT,
                                               rsa_provider             VARCHAR(150),
                                               beneficiary_no           VARCHAR(50),
                                               cust_class               INT,
                                               client_voh_no            INT,
                                               client_voh_year          INT,
                                               client_voh_type          INT,
                                               agent_voh_no             INT,
                                               agent_voh_year           INT,
                                               agent_voh_type           INT,
                                               rsa_prem                 FLOAT,
                                               loading                  FLOAT,
                                               no_of_clm                INT,
                                               tot_incurred             FLOAT,
                                               tariff_pkg               INT,
                                               user_name                VARCHAR(250),
                                               endo_serial              VARCHAR(50),
                                               vat_pcnt                 FLOAT,
                                               vat_amt                  FLOAT,
                                               final_tot_amt            FLOAT,
                                               vat_comm_pcnt            FLOAT,
                                               vat_comm_amt             FLOAT,
                                               file_no                  VARCHAR(50))""")   

mycursor.execute("""CREATE TABLE requests (timestamp        DATETIME,
                                           mobile           VARCHAR(50),
                                           pol_no           INT,
                                           pol_year         INT,
                                           pay_status       VARCHAR(50),
                                           trans_id         VARCHAR(50))""")
                                           
mysqldb.close()                                           